spring:
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            clientId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            authorizationGrantType: authorization_code
            redirectUri: "http://localhost:8081/login/oauth2/code/gateway"
            scope: openid
        provider:
          my-provider:
            issuerUri: "http://localhost:8080/realms/madeeasy-test-user-service"
server:
  port: 8081

